// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBatoMkcqcYgDtrCz7O0sxu2-vGrvmB2AI',
    appId: '1:573912942740:web:aa32f7caf5dd684f1a4c81',
    messagingSenderId: '573912942740',
    projectId: 'firestore-with-bloc',
    authDomain: 'firestore-with-bloc.firebaseapp.com',
    storageBucket: 'firestore-with-bloc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEQ2jKLzgRyjqRXJRqczg4PQQ9_j6co6I',
    appId: '1:573912942740:android:347769a186fc102f1a4c81',
    messagingSenderId: '573912942740',
    projectId: 'firestore-with-bloc',
    storageBucket: 'firestore-with-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjzxux2XN7zeehszGA_9bxJn8ixUi2QSY',
    appId: '1:573912942740:ios:42e60d6361672b911a4c81',
    messagingSenderId: '573912942740',
    projectId: 'firestore-with-bloc',
    storageBucket: 'firestore-with-bloc.appspot.com',
    iosBundleId: 'com.example.firestoreWithBloc',
  );
}
